set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN R1 [get_ports rst]
set_property PACKAGE_PIN P1 [get_ports set1]
set_property PACKAGE_PIN P2 [get_ports sure]
set_property PACKAGE_PIN P5 [get_ports check]
set_property PACKAGE_PIN A21 [get_ports led0]
set_property PACKAGE_PIN N19 [get_ports led1]
set_property PACKAGE_PIN N20 [get_ports led2]
set_property PACKAGE_PIN M20 [get_ports led3]
set_property -dict {PACKAGE_PIN K4 IOSTANDARD LVCMOS33} [get_ports {row[0]}]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports {row[1]}]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS33} [get_ports {row[2]}]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS33} [get_ports {row[3]}]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports {col[0]}]
set_property -dict {PACKAGE_PIN K6 IOSTANDARD LVCMOS33} [get_ports {col[1]}]
set_property -dict {PACKAGE_PIN J6 IOSTANDARD LVCMOS33} [get_ports {col[2]}]
set_property -dict {PACKAGE_PIN L5 IOSTANDARD LVCMOS33} [get_ports {col[3]}]
set_property PACKAGE_PIN F15 [get_ports led[6]]
set_property PACKAGE_PIN F13 [get_ports led[5]]
set_property PACKAGE_PIN F14 [get_ports led[4]]
set_property PACKAGE_PIN F16 [get_ports led[3]]
set_property PACKAGE_PIN E17 [get_ports led[2]]
set_property PACKAGE_PIN C14 [get_ports led[1]]
set_property PACKAGE_PIN C15 [get_ports led[0]]
set_property PACKAGE_PIN A18 [get_ports led_en[7]]
set_property PACKAGE_PIN A20 [get_ports led_en[6]]
set_property PACKAGE_PIN B20 [get_ports led_en[5]]
set_property PACKAGE_PIN E18 [get_ports led_en[4]]
set_property PACKAGE_PIN F18 [get_ports led_en[3]]
set_property PACKAGE_PIN D19 [get_ports led_en[2]]
set_property PACKAGE_PIN E19 [get_ports led_en[1]]
set_property PACKAGE_PIN C19 [get_ports led_en[0]]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports set1]
set_property IOSTANDARD LVCMOS33 [get_ports sure]
set_property IOSTANDARD LVCMOS33 [get_ports check]
set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led_en[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led_en[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led_en[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led_en[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led_en[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led_en[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led_en[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led_en[7]]
set_property IOSTANDARD LVCMOS33 [get_ports led0]
set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led2]
set_property IOSTANDARD LVCMOS33 [get_ports led3]